-- V12: Create category table and seed from spec/seed_data/category.csv
-- Stores product category names (e.g. 蘇打餅, 捲心酥) for reference and filtering

CREATE TABLE category (
    id          INT             NOT NULL AUTO_INCREMENT,
    name        VARCHAR(200)    NOT NULL,
    created_at  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_category_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Seed from category.csv (52 rows)
INSERT INTO category (name) VALUES
('蘇打餅'),
('(半)綜合半成品'),
('捲心酥'),
('(半)捲心酥半成品'),
('西點'),
('派&滾印餅乾'),
('(半)西點半成品'),
('(半)派&滾印餅乾半成品'),
('煎餅'),
('(半)煎餅半成品'),
('捲心餅'),
('(半)捲心餅半成品'),
('法國酥'),
('(半)法國酥半成品'),
('綜合'),
('河馬餅'),
('(半)河馬餅半成品'),
('口栓袋'),
('大果凍'),
('優酪'),
('大果凍2'),
('(半)大果凍2'),
('凍飲75mm'),
('(半)DR.Q蒟蒻袋裝'),
('(半)27g果凍半成品'),
('(半)35g果凍半成品'),
('(半)珍珠吉果半成品'),
('(半)優酪半成品'),
('(半)小果凍半成品'),
('27g果凍'),
('35g果凍'),
('小果凍'),
('珍珠吉果'),
('袋裝果凍Dr.Q'),
('乾果&堅果綜合'),
('走遍天下'),
('夾心酥'),
('巧克酥'),
('(半)夾心酥半成品'),
('(半)巧克酥半成品'),
('(半)黑瓜子半成品'),
('(半)南瓜子半成品'),
('(半)開心果半成品'),
('(半)葵瓜子半成品'),
('(半)乾果半成品'),
('(半)糖果半成品'),
('糖果零嘴'),
('(半)走遍天下半成品'),
('黑瓜子'),
('南瓜子'),
('開心果'),
('葵瓜子');
